services:
  git_server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    container_name: mcp-git-server
    ports:
    - 8000:8000
    volumes:
    - ./logs:/tmp
    environment:
    - MCP_SERVER_NAME=git_server
    command: --transport streamable-http
    restart: unless-stopped
    networks:
    - mcp-network
    healthcheck:
      test:
      - CMD
      - curl
      - -f
      - http://localhost:8000/health
      interval: 30s
      timeout: 10s
      retries: 3
  code_remediation_server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    container_name: mcp-code-remediation-server
    ports:
    - 8001:8001
    volumes:
    - ./logs:/tmp
    environment:
    - MCP_SERVER_NAME=code_remediation_server
    - RESULTS_BUCKET=${RESULTS_BUCKET}
    command: --transport streamable-http
    restart: unless-stopped
    networks:
    - mcp-network
    healthcheck:
      test:
      - CMD
      - curl
      - -f
      - http://localhost:8001/health
      interval: 30s
      timeout: 10s
      retries: 3
  aws_utils_server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    container_name: mcp-aws-utils-server
    ports:
    - 8002:8002
    volumes:
    - ./logs:/tmp
    environment:
    - MCP_SERVER_NAME=aws_utils_server
    command: --transport streamable-http
    restart: unless-stopped
    networks:
    - mcp-network
    healthcheck:
      test:
      - CMD
      - curl
      - -f
      - http://localhost:8002/health
      interval: 30s
      timeout: 10s
      retries: 3
  servicenow_server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    container_name: mcp-servicenow-server
    ports:
    - 8003:8003
    volumes:
    - ./logs:/tmp
    environment:
    - MCP_SERVER_NAME=servicenow_server
    command: --transport streamable-http
    restart: unless-stopped
    networks:
    - mcp-network
    healthcheck:
      test:
      - CMD
      - curl
      - -f
      - http://localhost:8003/health
      interval: 30s
      timeout: 10s
      retries: 3
  jira_server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    container_name: mcp-jira-server
    ports:
    - 8004:8004
    volumes:
    - ./logs:/tmp
    environment:
    - MCP_SERVER_NAME=jira_server
    command: --transport streamable-http
    restart: unless-stopped
    networks:
    - mcp-network
    healthcheck:
      test:
      - CMD
      - curl
      - -f
      - http://localhost:8004/health
      interval: 30s
      timeout: 10s
      retries: 3
  env_lookup_server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    container_name: mcp-env-lookup-server
    ports:
    - 8005:8005
    volumes:
    - ./logs:/tmp
    environment:
    - MCP_SERVER_NAME=env_lookup_server
    command: --transport streamable-http
    restart: unless-stopped
    networks:
    - mcp-network
    healthcheck:
      test:
      - CMD
      - curl
      - -f
      - http://localhost:8005/health
      interval: 30s
      timeout: 10s
      retries: 3
networks:
  mcp-network:
    driver: bridge
    ipam:
      config:
      - subnet: 172.21.0.0/16
